# Generated by Django 4.1.5 on 2023-02-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atakumbungalov', '0007_alter_anasayfahizmetler_options_alter_galeri_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeri',
            name='anasayfa_active',
            field=models.BooleanField(default=False, verbose_name='Anasayfada Görünsün mü'),
        ),
    ]
