# Generated by Django 4.1.5 on 2023-02-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atakumbungalov', '0008_alter_galeri_anasayfa_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnasayfaOdalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=50, verbose_name='Oda İsmi')),
                ('ozellik1', models.CharField(max_length=50, verbose_name='1. Özellik')),
                ('ozellik2', models.CharField(max_length=50, verbose_name='2. Özellik')),
                ('ozellik3', models.CharField(max_length=50, verbose_name='3. Özellik')),
                ('ozellik4', models.CharField(max_length=50, verbose_name='4. Özellik')),
                ('buyukresim', models.ImageField(upload_to='oda')),
                ('kucukresim', models.ImageField(upload_to='oda')),
            ],
            options={
                'verbose_name': 'Oda Bilgi',
                'verbose_name_plural': 'Oda Bilgi',
            },
        ),
    ]
